package com.abctreinamentos;
// Generated 17/09/2017 06:21:14 by Hibernate Tools 4.3.1


/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private long codcurso;
     private String nome;
     private long valor;
     private String url;

    public Curso() {
    }

    public Curso(long codcurso, String nome, long valor, String url) {
       this.codcurso = codcurso;
       this.nome = nome;
       this.valor = valor;
       this.url = url;
    }
   
    public long getCodcurso() {
        return this.codcurso;
    }
    
    public void setCodcurso(long codcurso) {
        this.codcurso = codcurso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public long getValor() {
        return this.valor;
    }
    
    public void setValor(long valor) {
        this.valor = valor;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        return "Curso{" + "codcurso=" + codcurso + ", nome=" + nome + ", valor=" + valor + ", url=" + url + '}';
    }

    


}


