package com.abctreinamentos;
// Generated 17/09/2017 06:21:14 by Hibernate Tools 4.3.1


/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId  implements java.io.Serializable {


     private long cpf;
     private long codcurso;

    public PagamentoId() {
    }

    public PagamentoId(long cpf, long codcurso) {
       this.cpf = cpf;
       this.codcurso = codcurso;
    }
   
    public long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(long cpf) {
        this.cpf = cpf;
    }
    public long getCodcurso() {
        return this.codcurso;
    }
    
    public void setCodcurso(long codcurso) {
        this.codcurso = codcurso;
    }

    @Override
    public String toString() {
        return "PagamentoId{" + "cpf=" + cpf + ", codcurso=" + codcurso + '}';
    }
    
    
}